PagePerfect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('member/', include('member.urls')),
    path('writer/', include("writer.urls")),
    path('employee/', include("employee.urls")),
    path('auth/', include("authentication.urls"))
]

book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_boks'),
]

employee/urls.py
from django.urls import path
from .views import add_book_stock, get_active_json, get_books_for_employee, get_catalog_json, main, catalogBook, bookFromWriter, test, getBook, mainBook, mainBookFromWriter, mainSetBook, setBook, accBookFromWriter, denBookFromWriter, showingToMember, notShowingToMember, employee_page, toggle_catalog_visibility, update_book_status
from .views import main, catalogBook, bookFromWriter, test, getBook, mainBook, mainBookFromWriter, mainSetBook, setBook, accBookFromWriter, denBookFromWriter, showingToMember, notShowingToMember, mainCatalog

app_name = 'employee'

urlpatterns = [
    path('main', main, name='main'),
    path('catalog', mainCatalog, name='catalog'),
    path('set-book', mainSetBook, name='mainSetBook'),
    path('book-from-writer', mainBookFromWriter, name='mainBookFromWriter'),
    path('book/<int:book_id>', mainBook, name='bookFromWriter'),
    path('api/catalog', catalogBook, name='catalogBook'),
    path('api/acc', bookFromWriter, name='bookFromWriter'),
    path('api/book/<int:book_id>', getBook, name='bookFromWriter'),
    path('api/set', setBook, name='setBook'),
    path('acceptBook', accBookFromWriter, name='acceptBook'),
    path('deniedBook', denBookFromWriter, name='deniedBook'),
    path('show', showingToMember, name='showingToMember'),
    path('notshow', notShowingToMember, name='notShowingToMember'),
    path('test', test, name='test'),
    path('get-book-json/', get_books_for_employee, name='get_books_for_employee'),
    path('get-catalog-json/', get_catalog_json, name='get_catalog_json'),
    path('get-active-json/', get_active_json, name='get_active_json'),
    path('catalog/toggle-visibility/<int:pk>/', toggle_catalog_visibility, name='toggle-catalog-visibility'),
    path('update-book-status/<int:book_id>/<str:status>/', update_book_status, name='update_book_status'),
    path('add-book-stock/', add_book_stock, name='add_book_stock'),
]

main/urls.py
from django.urls import path
from . import views
from main.views import register, login_user, landing, logout_user, show_mainMember, show_mainWriter, show_mainEmployee
app_name = 'main'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('mainMember/', show_mainMember, name='show_mainMember'),
    path('mainWriter/', show_mainWriter, name='show_mainWriter'),
    path('mainEmployee/', show_mainEmployee, name='show_mainEmployee'),
    path('logout/', logout_user, name='logout')
]

book/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    STATUS_CHOICES = [
        ("ACCEPT", 'Accept'),
        ("WAITING", 'Waiting'),
        ("DENIED", 'Denied')
    ]
    bookID = models.IntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    authors = models.TextField(null=True, blank=True)
    average_rating = models.FloatField(null=True, blank=True)
    isbn = models.TextField(null=True, blank=True)
    isbn13 = models.BigIntegerField(null=True, blank=True)
    language_code = models.TextField(null=True, blank=True)
    num_pages = models.IntegerField(null=True, blank=True)
    ratings_count = models.IntegerField(null=True, blank=True)
    text_reviews_count = models.IntegerField(null=True, blank=True)
    publication_date = models.TextField(null=True, blank=True)
    publisher = models.TextField(null=True, blank=True)
    harga = models.IntegerField(null=True, blank=True)
    jumlah_buku = models.IntegerField(null=True, blank=True)
    jumlah_terjual = models.IntegerField(default=0, blank=True)
    statusAccept = models.CharField(max_length=10, choices=STATUS_CHOICES, default="WAITING")
    isInCatalog = models.BooleanField(default=False)

employee/models.py
from django.db import models
from book.models import Book

# Create your models here.

class Catalog(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    isShowToMember = models.BooleanField(default=False)

    def __str__(self):
        return self.book.title

book/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from book.models import Book
# Create your views here.

def get_books(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

employee/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from book.models import Book
from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from .models import Catalog
from main.models import Employee
import json

# Create your views here.


#@login_required(login_url='login')

@login_required(login_url='/login')
def main(request):
    try :
        employee = Employee.objects.get(user=request.user.id)
        response = {
            "name" : request.user.username
        }
        return render(request, 'employee.html', response)
    except : 
        return render(request, 'failed.html')

@login_required(login_url='/login')
def mainCatalog(request):
    try :
        employee = Employee.objects.get(user=request.user.id)
        response = {}
        return render(request, 'catalog.html', response)
    except : 
        return render(request, 'failed.html')

@login_required(login_url='/login')
def mainBook(request, book_id):
    try :
        employee = Employee.objects.get(user=request.user.id)
        response = {"book_id" : book_id}
        return render(request, 'book.html', response)
    except : 
        return render(request, 'failed.html')

@login_required(login_url='/login')
def mainSetBook(request):
    try :
        employee = Employee.objects.get(user=request.user.id)
        response = {}
        return render(request, 'setBook.html', response)
    except : 
        return render(request, 'failed.html')

@login_required(login_url='/login')
def mainBookFromWriter(request):
    try :
        employee = Employee.objects.get(user=request.user.id)
        response = {}
        return render(request, 'bookFromWriter.html', response)
    except : 
        return render(request, 'failed.html')

@login_required(login_url='/login')
def accBookFromWriter(request):
    if request.method == 'POST' :
        book_id = request.POST.get('book_id')
        try:
            instance = Book.objects.get(bookID=book_id)
            instance.statusAccept = "ACCEPT"
            instance.save()

            catalog= Catalog.objects.create(
                 book=instance,
            )
            return HttpResponse({'status': 'The book ' + instance.title + ' was accepted'} , status=200)
        except Book.DoesNotExist:
            return HttpResponse({'status': 'Error: Object not found'}, status=404)
    return HttpResponse({'status': 'Error: Invalid request'}, status=400)

@login_required(login_url='/login')
def denBookFromWriter(request):
    if request.method == 'POST' :
        book_id = request.POST.get('book_id')
        try:
            instance = Book.objects.get(bookID=book_id)
            instance.statusAccept = "DENIED"
            instance.save()
            return HttpResponse({'status': 'The book ' + instance.title + ' was denied'} , status=200)
        except Book.DoesNotExist:
            return HttpResponse({'status': 'Error: Object not found'}, status=404)
    return HttpResponse({'status': 'Error: Invalid request'}, status=400)

@login_required(login_url='/login')
def catalogBook(request):
    data = Catalog.objects.all()
    catalog_data = []
    for entry in data:
        book = Book.objects.filter(bookID = entry.book.bookID).all()
        for book_instance in book:
            catalog_data.append({
                'Catalog' : entry.pk,
                'isShow' : entry.isShowToMember,
                'bookID': book_instance.bookID,
                'title': book_instance.title,
                'authors' : book_instance.authors,
                'average_rating' : book_instance.average_rating,
                'jumlah_buku' : book_instance.jumlah_buku,
                'jumlah_terjual' : book_instance.jumlah_terjual
                # Include other fields you want to serialize
            })

    json_data = json.dumps(list(catalog_data))

    return HttpResponse(json_data, content_type="application/json")

@login_required(login_url='/login')
def showingToMember(request):
    if request.method == 'POST' :
        catalog_id = request.POST.get('catalog_id')
        try:
            instance = Catalog.objects.filter(pk= catalog_id).update(isShowToMember=True)
            return HttpResponse({'status': 'The book ' + ' was showed'} , status=200)
        except Book.DoesNotExist:
            return HttpResponse({'status': 'Error: Object not found'}, status=404)
    return HttpResponse({'status': 'Error: Invalid request'}, status=400)

@login_required(login_url='/login')
def notShowingToMember(request):
    if request.method == 'POST' :
        catalog_id = request.POST.get('catalog_id')
        try:
            instance = Catalog.objects.filter(pk= catalog_id).update(isShowToMember=False)
            return HttpResponse({'status': 'The book ' + ' was not showed'} , status=200)
        except Book.DoesNotExist:
            return HttpResponse({'status': 'Error: Object not found'}, status=404)
    return HttpResponse({'status': 'Error: Invalid request'}, status=400)

@login_required(login_url='/login')
def getBook(request, book_id):
    data = Book.objects.filter(bookID = book_id).all()
    print(data)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def bookFromWriter(request):
    data = Book.objects.filter(statusAccept = "WAITING").all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def setBook(request):
    data = Book.objects.filter(statusAccept = "ACCEPT").all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def test(request):
    data = Catalog.objects.filter(isShowToMember = True).all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# Tambahan buat bisa akses employee.html dari views.py di main
def employee_page(request):
    return render(request, 'employee.html')

def get_books_for_employee(request):
    books = Book.objects.filter(pk__lte=100, statusAccept ="WAITING")[:100]
    books_data = serializers.serialize('json', books)
    books_list = json.loads(books_data)
    return JsonResponse(books_list, safe=False)

def get_catalog_json(request):
    books = Book.objects.filter(pk__lte=100, statusAccept ="ACCEPT")[:100]
    books_data = serializers.serialize('json', books)
    books_list = json.loads(books_data)
    return JsonResponse(books_list, safe=False)

def get_active_json(request):
    catalog = Catalog.objects.all()
    catalog_data = serializers.serialize('json', catalog)
    catalog_list = json.loads(catalog_data)
    return JsonResponse(catalog_list, safe=False)

@csrf_exempt
def update_book_status(request, book_id, status):
    if request.method == 'POST':
        book = get_object_or_404(Book, pk=book_id)
        if status in [choice[0] for choice in Book.STATUS_CHOICES]:
            book.statusAccept = status
            catalog= Catalog.objects.create(
                book=book,
            )
            catalog.save()
            book.save()
            return JsonResponse({'status': 'success', 'message': 'Book status updated'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Invalid status'}, status=400)
    return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

@csrf_exempt
def add_book_stock(request):
    if request.method == "POST":
        data = request.POST
        book_id = data.get('book_id')
        added_stock = int(data.get('added_stock'))

        try:
            book = Book.objects.get(pk=book_id)
            book.jumlah_buku += added_stock
            book.save()
            return JsonResponse({'status': 'success', 'new_stock': book.jumlah_buku})
        except Book.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Book not found'}, status=404)

    return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)

@csrf_exempt
def toggle_catalog_visibility(request, pk):
    if request.method == 'POST':
        try:
            catalog_entry = Catalog.objects.get(pk=pk)
            catalog_entry.isShowToMember = not catalog_entry.isShowToMember
            catalog_entry.save()
            return JsonResponse({'success': True, 'isShowToMember': catalog_entry.isShowToMember})
        except Catalog.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Catalog not found'}, status=404)
    else:
        return HttpResponseNotAllowed(['POST'])

employee/templates/book.html
{% extends 'base.html' %}
{% load static %}
    
{% block meta %} 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
{% endblock %}
{% block content %} 
<header class="header">
  <nav class="navbar navbar-expand-lg bg-primary">
      <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'employee:main' %}">PagePerfect</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> 
                  <li class="nav-item d-flex">
                      <a class="btn btn-danger me-2" href="{% url 'main:logout' %}" role="button">Logout</a> 
                  </li>
              </ul>
          </div>
      </div>
  </nav>
</header>
    <div class="container mt-5">
        <button class="btn btn-primary" onclick="Back()">Back</button>
        <div id="data-container">
            
        </div>
        
    </div>


<script>
    function Back() {
            window.history.back();
        }
    $(document).ready(function() {
        var id = '{{ book_id }}'
        $.ajax({
            url: '../api/book/' + id ,  
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                // Handle the returned data here

                for (var i = 0; i < data.length; i++) {
                    var item = data[i];
                // Do something with each item, for example, append it to a list
                    $('#data-container').append(
                        "<div class=\"row\">" +
                        "<div class=\"col-12 text-center\">" +
                        "<h1>" + item.fields.title + "</h1>" +
                        "</div>" + 
                        "<table class=\"table\"> " +
                        "<thead>"+
                          "<tr>" +
                            "<th scope=\"col\"></th> " +
                            "<th scope=\"col\"></th> " +
                          "</tr> " + 
                        "</thead> " +
                        "<tbody id> " +
                            "<tr>" +
                                "<th scope=\"row\">Author</th>" +
                            "<td>" + item.fields.authors + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">Price</th>" +
                            "<td>" + item.fields.harga + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">Rating</th>" +
                            "<td>" + item.fields.average_rating + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">ISBN</th>" +
                            "<td>" + item.fields.isbn + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">Language</th>" +
                            "<td>" + item.fields.language_code + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">Num Pages</th>" +
                            "<td>" + item.fields.num_pages + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">Publication Date</th>" +
                            "<td>" + item.fields.publication_date + "</td>" +
                          "</tr>" +
                          "<tr>" +
                            "<th scope=\"row\">Publisher</th>" +
                            "<td>" + item.fields.publisher + "</td>" +
                          "</tr>" +
                        "</tbody> " +
                      "</table>"
                        
                        );
                }
            },
            error: function(error) {
                console.log(error);
            }
        });
    });
</script>
{% endblock %}

employee/templates/bookFromWriter.html
{% extends 'base.html' %}
{% load static %}
    
{% block meta %} 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
{% endblock %}
{% block content %} 
<header class="header">
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'employee:main' %}">PagePerfect</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> 
                    <li class="nav-item d-flex">
                        <a class="btn btn-danger me-2" href="{% url 'main:logout' %}" role="button">Logout</a> 
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="container mt-5">
        <button class="btn btn-primary" onclick="Back()">Back</button>
        <div class="d-grid gap-2 col-6 mx-auto">
            <div class="row">
                    <div class="col-12 text-center">
                        <h1>Book From Writer</h1>
                    </div>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">No</th>
                            <th scope="col">Title</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                          </tr>
                        </thead>
                        <tbody id ='data-container'>
                        </tbody>
                      </table>
                </div>
        

    
</div>
    </div>

<script>
    function Back() {
            window.history.back();
        }

    function acceptBook(bookID) {
    $.ajax({
        type: 'POST',
        url: 'acceptBook',  // Replace with your actual POST URL endpoint
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            book_id: bookID
        },
        success: function(response) {
            console.log('The book was accepted');
            location.reload();
        },
        error: function() {
            console.error('Failed to perform POST request.');
        }
    });
}

    function denyBook(bookID) {
    $.ajax({
        type: 'POST',
        url: 'deniedBook',  // Replace with your actual POST URL endpoint
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            book_id: bookID
        },
        success: function(response) {
            console.log('The book was denied');
            location.reload();
        },
        error: function() {
            console.error('Failed to perform POST request.');
        }
    });
}
    $(document).ready(function() {
        $.ajax({
            url: 'api/acc',  
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                // Handle the returned data here

                for (var i = 0; i < data.length; i++) {
                    var item = data[i];
                    var buttonA = $('<button>').text('Accepted');
                    
                        buttonA.click(function(){
                        // Perform AJAX POST request when the button is clicked
                        $.ajax({
                            type: 'POST',
                            url: 'acceptBook',  // Replace with your actual POST URL endpoint
                            data: {
                                csrfmiddlewaretoken: '{{ csrf_token }}',
                                book_id: item.fields.bookID // Include any necessary data for the POST request
                            },
                            success: function(response){
                                // Handle success response
                                console.log('The book was accepted');
                                location.reload();
                            },
                            error: function(){
                                // Handle error if the AJAX request fails
                                console.error('Failed to perform POST request.');
                            }
                        });
                    });
                        


                    var buttonD = $('<button>').text('Denied');

                        buttonD.click(function(){
                        // Perform AJAX POST request when the button is clicked
                        $.ajax({
                            type: 'POST',
                            url: 'deniedBook',  // Replace with your actual POST URL endpoint
                            data: {
                                csrfmiddlewaretoken: '{{ csrf_token }}',
                                book_id: item.fields.bookID // Include any necessary data for the POST request
                            },
                            success: function(response){
                                // Handle success response
                                console.log('The book was accepted');
                                location.reload();
                            },
                            error: function(){
                                // Handle error if the AJAX request fails
                                console.error('Failed to perform POST request.');
                            }
                        });
                    });
                // Do something with each item, for example, append it to a list

                    $('#data-container').append(
                    "<tr>" +
                        "<th scope=\"row\">" + (i+1) + "</th>" +
                            "<td>" + item.fields.title + "</td>" +

                            "<td> <a class=\"btn btn-primary\" href=\"book/" + item.fields.bookID + "\" role=\"button\">DETAIL</a> </td>" +
                            "<td><button class=\"btn btn-success\" onclick=\"acceptBook(" + item.fields.bookID + ")\">ACCEPT</button></td>" +
                            "<td><button class=\"btn btn-danger\" onclick=\"denyBook(" + item.fields.bookID + ")\">DENIED</button></td>" +
                            "</tr>"
                          );
                
            
                }
            },
            error: function(error) {
                console.log(error);
            }
        });
    });
</script>
{% endblock %}

employee/templates/catalog.html
{% extends 'base.html' %}
{% load static %}
    
{% block meta %} 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
{% endblock %}
{% block content %} 
<header class="header">
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'employee:main' %}">PagePerfect</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> 
                    <li class="nav-item d-flex">
                        <a class="btn btn-danger me-2" href="{% url 'main:logout' %}" role="button">Logout</a> 
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="container mt-5">
        <button class="btn btn-primary" onclick="Back()">Back</button>
        <div class="d-grid gap-2 col-6 mx-auto">
            <div class="row">
                    <div class="col-12 text-center">
                        <h1>Main Catalog</h1>
                    </div>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">No</th>
                            <th scope="col">Title</th>
                            <th scope="col">Stock</th>
                            <th scope="col">Sold</th>
                            <th scope="col">Details</th>
                            <th scope="col">Add Stock</th>
                          </tr>
                        </thead>
                        <tbody id ='data-container'>
                        </tbody>
                      </table>
                </div>
        

<body>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Book to Cart</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="title" class="col-form-label">Title:</label>
                            <input type="text" class="form-control" id="title" name="title" readonly></input>
                        </div>
                        <div class="mb-3">
                            <label for="quantity" class="col-form-label">Add Stock:</label>
                            <div class="input-group">
                                <button type="button" class="btn btn-secondary" onclick="decrementQuantity()">-</button>
                                <input type="text" class="form-control text-center" id="quantity" name="quantity" value="1">
                                <button type="button" class="btn btn-secondary" onclick="incrementQuantity()">+</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_form" data-bs-dismiss="modal">Add Book</button>
                </div>
            </div>
        </div>
    </div>

</body>
</div>
    </div>


<script>
    function Back() {
            window.history.back();
        }
    $(document).ready(function() {
        $.ajax({
            url: 'api/catalog',  
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                // Handle the returned data here

                for (var i = 0; i < data.length; i++) {
                    var item = data[i];
                // Do something with each item, for example, append it to a list
                $('#data-container').append(
                    "<tr>" +
                        "<th scope=\"row\">" + (i+1) + "</th>" +
                            "<td>" + item.title + "</td>" +
                            "<td>" + item.jumlah_buku + "</td>" +
                            "<td>" + item.jumlah_terjual + "</td>" +

                            "<td>" + 
                                "<a class=\"btn btn-primary\" href=\"book/" + item.bookID + "\" role=\"button\">DETAIL</a> " +
                            "</td>" +        
                            "<td>" + 
                                "<button class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\" data-book-title=\"" + item.title + "\" onclick=\"setBookTitleInModal(this)\">Add</button>" + 
                            "</td>" +        
                          "</tr>"
                          );
                
                }
            },
            error: function(error) {
                console.log(error);
            }
        });
    });

    function setBookTitleInModal(buttonElement) {
        var bookTitle = buttonElement.getAttribute('data-book-title');
        document.getElementById('title').value = bookTitle;
        document.getElementById('quantity').value = 1; // Set default quantity to 1
    }

    function incrementQuantity() {
        var quantityInput = document.getElementById('quantity');
        var currentQuantity = parseInt(quantityInput.value);
        quantityInput.value = currentQuantity + 1;
    }

    function decrementQuantity() {
        var quantityInput = document.getElementById('quantity');
        var currentQuantity = parseInt(quantityInput.value);
        if (currentQuantity > 1) {
            quantityInput.value = currentQuantity - 1;
        }
    }



</script>
{% endblock %}