PagePerfect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('member/', include('member.urls')),
    path('writer/', include("writer.urls")),
    path('employee/', include("employee.urls")),
    path('auth/', include("authentication.urls"))
]

book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_boks'),
]

main/urls.py
from django.urls import path
from . import views
from main.views import register, login_user, landing, logout_user, show_mainMember, show_mainWriter, show_mainEmployee
app_name = 'main'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('mainMember/', show_mainMember, name='show_mainMember'),
    path('mainWriter/', show_mainWriter, name='show_mainWriter'),
    path('mainEmployee/', show_mainEmployee, name='show_mainEmployee'),
    path('logout/', logout_user, name='logout')
]

writer/urls.py
from django.urls import path
from . import views

app_name = 'writer'

urlpatterns = [
    path('get-product/', views.get_book_json, name="get_book_json"),
    path('get-acc-product/', views.get_acc_book_json, name="get_acc_book_json"),
    path('get-waiting-product/', views.get_waiting_book_json, name="get_waiting_book_json"),
    path('get-denied-product/', views.get_denied_book_json, name="get_denied_book_json"),
    path('create-product-ajax/', views.add_book_ajax, name="add_book_ajax"),
    path('show-collection/', views.show_collection, name="show_collection"),
    path('show-status-book/', views.show_status_book, name="show_status_book"),
    path('show-revenue/', views.show_revenue, name="show_revenue"),
    path('json/', views.show_json, name='show_json'),
    path('create-flutter/', views.create_product_flutter, name='create_product_flutter'),
]

writer/views.py
import json
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.contrib import messages  
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from book.models import Book
from django.core import serializers
# Create your views here.
@csrf_exempt
def add_book_ajax(request):
    if request.method == "POST":
        title = request.POST.get("title")
        harga = request.POST.get("harga")
        jumlah_buku = request.POST.get("jumlah_buku")
        
        new_book = Book(title=title, authors=request.user.username, harga=harga, jumlah_buku=jumlah_buku, statusAccept='WAITING')
        new_book.save()
        new_book.bookID = new_book.pk + 80
        new_book.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Book.objects.create(
            title = data["title"],
            authors = request.user.username,
            harga = int(data["harga"]),
            jumlah_buku = int(data["jumlah_buku"]),
            statusAccept = data["statusAccept"]
        )
        

        new_product.save()
        new_product.bookID = new_product.pk + 80
        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

def get_book_json(request):
    books_item = Book.objects.all().filter(authors=request.user.username)
    return HttpResponse(serializers.serialize('json', books_item))


def get_acc_book_json(request):
    acc_books_item = Book.objects.all().filter(authors=request.user.username).filter(statusAccept='ACCEPT')
    return HttpResponse(serializers.serialize('json', acc_books_item))


def get_waiting_book_json(request):
    waiting_books_item = Book.objects.all().filter(authors=request.user.username).filter(statusAccept='WAITING')
    return HttpResponse(serializers.serialize('json', waiting_books_item))


def get_denied_book_json(request):
    denied_books_item = Book.objects.all().filter(authors=request.user.username).filter(statusAccept='DENIED')
    return HttpResponse(serializers.serialize('json', denied_books_item))


def show_collection(request):
    context = {
        'name' : request.user.username,
    }
    return render(request, 'show_collection.html', context)


def show_status_book(request):
    context = {
        'name' : request.user.username,
    }
    return render(request, 'show_status_book.html', context)


def show_revenue(request):
    books_item = Book.objects.all().filter(authors=request.user.username)
    total_revenue = 0
    for book in books_item:
        total_revenue += book.harga * book.jumlah_terjual
    context = {
        'name' : request.user.username,
        'total_revenue' : total_revenue
    }
    return render(request, 'show_revenue.html', context)


def show_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

writer/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PagePerfect</title>

    {% block meta %}
    {% endblock meta %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}">
</head>
<body>
    

    {% block content %}
    {% endblock content %}
</body>
</html>

writer/templates/show_collection.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
        }
        .row {
            justify-content: center;
            gap: 20px;
        }
        .card {
            text-align: center;
            margin: 5px;
            width: 395px; 
            height: 300px; 
            background-color: #f5f5f5; /* Background color */
            border: 1px solid #ddd; /* Border color */
            border-radius: 10px; /* Rounded corners */
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle lift effect */
        }
        .card-title {
            font-size: 24px; /* Title font size */
            color: #333; /* Title text color */
            font-family: 'Times New Roman', sans-serif; /* Title font family */
        }

        .card-text {
            font-size: 16px; /* Text font size */
            color: #555; /* Text color */
            font-family: 'Arial', sans-serif; /* Text font family */
        }
    </style>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
              <a class="navbar-brand" href="#">{{ name }}</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a href = "{% url 'main:show_mainWriter' %}">
                        <button type="button" class="btn btn-info btn-sm" style="margin-left: 10px;">Main Page</button>
                    </a>
                    <a href = "{% url 'writer:show_status_book' %}">
                        <button type="button" class="btn btn-success btn-sm" style="margin-left: 10px;">Book Status</button>
                    </a>
                    <a href = "{% url 'writer:show_revenue' %}">
                        <button type="button" class="btn btn-warning btn-sm" style="margin-left: 10px;">Book Revenue</button>
                    </a>
                    <a href="{% url 'main:logout' %}">
                        <button type="button" class="btn btn-danger btn-sm" style="margin-left: 10px;">Logout</button>
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <br>

    <div class="card-container">
        <div class='row' id="product_cards"></div>
    </div>


    <script>
        async function getBooks() {
            return fetch("{% url 'writer:get_book_json' %}").then((res) => res.json())
        }

        async function refreshBooks() {
            document.getElementById("product_cards").innerHTML = "";
            const books = await getBooks();
            let htmlString = "";
            books.forEach((book) => {
                htmlString += `
                <div class="card col-md-4">
                    <div class="card-body">
                        <h5 class="card-title">${book.fields.title}</h5>
                        <p class="card-text">Author: ${book.fields.authors}</p>
                        <p class="card-text">Price: ${book.fields.harga}</p>
                        <p class="card-text">Stock: ${book.fields.jumlah_buku}</p>
                        <p class="card-text">Sold: ${book.fields.jumlah_terjual}</p>
                    </div>
                </div>`;
            });
            document.getElementById("product_cards").innerHTML = htmlString;
            
        }
          refreshBooks()

    </script>

{% endblock content %}

writer/templates/show_revenue.html
{% extends 'base.html' %}

{% block content %}

<style>
    h2 {
        text-align: center;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    #total_amount {
        color : rgb(255, 89, 0);
        font-size: 30px;
        font-weight: lighter;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .card-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 20px;
    }
    .row {
        justify-content: center;
        gap: 20px;
    }
    .card {
        text-align: center;
        margin: 5px;
        width: 395px; 
        height: 300px; 
        background-color: #f5f5f5; /* Background color */
        border: 1px solid #ddd; /* Border color */
        border-radius: 10px; /* Rounded corners */
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle lift effect */
    }
    .card-title {
        font-size: 24px; /* Title font size */
        color: #333; /* Title text color */
        font-family: 'Times New Roman', sans-serif; /* Title font family */
    }

    .card-text {
        font-size: 16px; /* Text font size */
        color: #555; /* Text color */
        font-family: 'Arial', sans-serif; /* Text font family */
    }

</style>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
          <a class="navbar-brand" href="#">{{ name }}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a href = "{% url 'main:show_mainWriter' %}">
                    <button type="button" class="btn btn-info btn-sm" style="margin-left: 10px;">Main Page</button>
                </a>
                <a href = "{% url 'writer:show_collection' %}">
                    <button type="button" class="btn btn-success btn-sm" style="margin-left: 10px;">Creation Library</button>
                </a>
                <a href = "{% url 'writer:show_status_book' %}">
                    <button type="button" class="btn btn-warning btn-sm" style="margin-left: 10px;">Book Status</button>
                </a>
                <a href="{% url 'main:logout' %}">
                    <button type="button" class="btn btn-danger btn-sm" style="margin-left: 10px;">Logout</button>
                </a>
            </div>
        </div>
    </div>
</nav>
<br>
<h2>Your Revenue : {{ total_revenue }}</h2>
<br>
<div class="card-container">
    <div class='row' id="product_cards"></div>
</div>

<script>
    async function getBooks() {
        return fetch("{% url 'writer:get_book_json' %}").then((res) => res.json())
    }

    async function refreshBooks() {
        document.getElementById("product_cards").innerHTML = "";
        const books = await getBooks();
        let htmlString = "";
        books.forEach((book) => {
            htmlString += `
            <div class="card col-md-4">
                <div class="card-body">
                    <h5 class="card-title">${book.fields.title}</h5>
                    <p class="card-text">Author: ${book.fields.authors}</p>
                    <p class="card-text">Price: ${book.fields.harga}</p>
                    <p class="card-text">Stock: ${book.fields.jumlah_buku}</p>
                    <p class="card-text">Sold: ${book.fields.jumlah_terjual}</p>
                </div>
            </div>`;
        });
        document.getElementById("product_cards").innerHTML = htmlString;
        
    }
      refreshBooks()
</script>

{% endblock content %}

writer/templates/show_status_book.html
{% extends 'base.html' %}
{%  block content %}

<style>
    .content-container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .card-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        flex-wrap: wrap;
        justify-content: center;
        gap: 20px;
    }

    .card {
        text-align: center;
        margin: 5px;
        width: 395px; 
        height: 300px; 
        background-color: #f5f5f5; /* Background color */
        border: 1px solid #ddd; /* Border color */
        border-radius: 10px; /* Rounded corners */
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle lift effect */
    }
    .card-title {
        font-size: 24px; /* Title font size */
        color: #333; /* Title text color */
        font-family: 'Times New Roman', sans-serif; /* Title font family */
    }

    .card-text {
        font-size: 16px; /* Text font size */
        color: #555; /* Text color */
        font-family: 'Arial', sans-serif; /* Text font family */
    }

    #Accepted {
        color : green;
        font-size: 30px;
        font-weight: lighter;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    #NA {
        color : red;
        font-size: 30px;
        font-weight: lighter;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    #Waiting {
        color : grey;
        font-size: 30px;
        font-weight: lighter;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

</style>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
          <a class="navbar-brand" href="#">{{ name }}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a href = "{% url 'main:show_mainWriter' %}">
                    <button type="button" class="btn btn-info btn-sm" style="margin-left: 10px;">Main Page</button>
                </a>
                <a href = "{% url 'writer:show_collection' %}">
                    <button type="button" class="btn btn-success btn-sm" style="margin-left: 10px;">Creation Library</button>
                </a>
                <a href = "{% url 'writer:show_revenue' %}">
                    <button type="button" class="btn btn-warning btn-sm" style="margin-left: 10px;">Book Revenue</button>
                </a>
                <a href="{% url 'main:logout' %}">
                    <button type="button" class="btn btn-danger btn-sm" style="margin-left: 10px;">Logout</button>
                </a>
            </div>
        </div>
    </div>
</nav>

<br>
<div class="content-container">
    <div class="card-container">
        <h2>
            <div id = "Accepted"></div>
        </h2>
        <h2>
            <div id = "NA"></div>
        </h2>
        <h2>
            <div id = "Waiting"></div>
        </h2>
        <div id = "acc_books"></div>
        <div id = "na_books"></div>
        <div id = "wa_books"></div>
    </div>
</div>

<script>
    async function getAccBooks() {
        return fetch("{% url 'writer:get_acc_book_json' %}").then((res) => res.json())
    }

    
    async function getNABooks() {
        return fetch("{% url 'writer:get_denied_book_json' %}").then((res) => res.json())
    }
    
    async function getWaitingBooks() {
        return fetch("{% url 'writer:get_waiting_book_json' %}").then((res) => res.json())
    }

    async function refreshBooks() {
        document.getElementById("product_cards").innerHTML = "";
        const books = await getBooks();
        let htmlString = "";
        books.forEach((book) => {
            htmlString += `
            <div class="card col-md-4">
                <div class="card-body">
                    <h5 class="card-title">${book.fields.title}</h5>
                    <p class="card-text">Author: ${book.fields.authors}</p>
                    <p class="card-text">Price: ${book.fields.harga}</p>
                    <p class="card-text">Stock: ${book.fields.jumlah_buku}</p>
                    <p class="card-text">Sold: ${book.fields.jumlah_terjual}</p>
                </div>
            </div>`;
        });
        document.getElementById("product_cards").innerHTML = htmlString;
        
    }
    refreshBooks()

    async function refreshAccBooks() {
        document.getElementById("acc_books").innerHTML = "";
        const products = await getAccBooks();
        let htmlString = "";
        products.forEach((book) => {
            htmlString += `
                <div class="card col-md-4">
                    <div class="card-body">
                        <h5 class="card-title">${book.fields.title}</h5>
                        <p class="card-text">Author: ${book.fields.authors}</p>
                        <p class="card-text">${book.fields.statusAccept}</p>
                    </div>
                </div>`;
            });
            document.getElementById("acc_books").innerHTML = htmlString;
            document.getElementById("Accepted").textContent = `Accepted`;
        }
    
        refreshAccBooks()
        
        async function refreshNABooks() {
            document.getElementById("na_books").innerHTML = "";
            const products = await getNABooks();
            let htmlString = "";
            products.forEach((book) => {
                htmlString += `
                    <div class="card col-md-4">
                        <div class="card-body">
                            <h5 class="card-title">${book.fields.title}</h5>
                            <p class="card-text">Author: ${book.fields.authors}</p>
                            <p class="card-text">${book.fields.statusAccept}</p>
                        </div>
                    </div>`;
                });
                document.getElementById("na_books").innerHTML = htmlString;
                document.getElementById("NA").textContent = `Denied`;
            }

        refreshNABooks()

        async function refreshWABooks() {
            document.getElementById("wa_books").innerHTML = "";
            const products = await getWaitingBooks();
            let htmlString = "";
            products.forEach((book) => {
                htmlString += `
                    <div class="card col-md-4">
                        <div class="card-body">
                            <h5 class="card-title">${book.fields.title}</h5>
                            <p class="card-text">Author: ${book.fields.authors}</p>
                            <p class="card-text">${book.fields.statusAccept}</p>
                        </div>
                    </div>`;
                });
                document.getElementById("wa_books").innerHTML = htmlString;
                document.getElementById("Waiting").textContent = `Waiting`;
            }
        refreshWABooks()

</script>

{% endblock content %}