PagePerfect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('member/', include('member.urls')),
    path('writer/', include("writer.urls")),
    path('employee/', include("employee.urls")),
    path('auth/', include("authentication.urls"))
]

book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_boks'),
]

main/urls.py
from django.urls import path
from . import views
from main.views import register, login_user, landing, logout_user, show_mainMember, show_mainWriter, show_mainEmployee
app_name = 'main'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('mainMember/', show_mainMember, name='show_mainMember'),
    path('mainWriter/', show_mainWriter, name='show_mainWriter'),
    path('mainEmployee/', show_mainEmployee, name='show_mainEmployee'),
    path('logout/', logout_user, name='logout')
]

member/urls.py
from django.contrib import admin
from django.urls import path, include
from book.views import get_books
from member.views import add_book_to_cart, add_book_to_cart_flutter, confirm_purchase, confirm_purchase_flutter, delete_cart, edit_cart, get_books_for_json, get_books_for_json_by_title, get_cart, show_cart_json, show_main, logout_user, get_books_json, show_books_bought, get_money, add_money, shopping_cart, show_purchased_item, show_transaction, add_money_flutter
app_name = 'member'

urlpatterns = [
    path('main/', show_main, name='show_main'),
    path('logout/', logout_user, name='logout_user'),
    path('show_books/', get_books_json, name="show_books"),
    path('show_books_bought/', show_books_bought, name="show_books_bought"),
    path('get_money/', get_money, name='get_money'),
    path('add_money/', add_money, name='add_money'),
    path('shopping_cart/', shopping_cart, name='shopping_cart' ),
    path('add_book_to_cart/', add_book_to_cart, name='add_book_to_cart'),
    path('add_book_to_cart_flutter/', add_book_to_cart_flutter, name='add_book_to_cart_flutter'),
    path('edit-cart/', edit_cart, name='edit_cart'),
    path('get-cart/', get_cart, name='get_cart'),
    path('delete-cart/<str:title>/', delete_cart, name='delete_cart'),
    path('confirm_purchase/', confirm_purchase, name='confirm_purchase'),
    path('confirm_purchase_flutter/', confirm_purchase_flutter, name='confirm_purchase_flutter'),
    path('get-book/', get_books, name='get_books'),
    path('show-transaction/', show_transaction, name='show_transaction'),
    path('show-cart-json/', show_cart_json, name='show_cart_json'),
    path('get-book-json/', get_books_for_json, name='get_books_for_json'),
    path('get-book-json/<str:title>/', get_books_for_json_by_title, name='get_books_for_json_by_title'),
    path('show-purchased-json/<int:id>/', show_purchased_item, name='show_purchased_item'),
    path('add-money-flutter/', add_money_flutter, name='add_money_flutter'),
]

member/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book
from main.models import Member
# Create your models here.
class BukuOrder(models.Model):
    book = models.OneToOneField(Book, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)

class Order(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    buku = models.ManyToManyField(BukuOrder)

    def get_keranjang_books(self):
        return self.buku.all()
    
    def get_keranjang_total(self):
        total = 0
        for buku in self.buku.all():
            total += buku.book.harga
        return total
    
class CartItem(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

class BoughtItem(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    cart = models.ManyToManyField(CartItem)
    notes = models.TextField(null=True, blank=True)

class PurchasedItem(models.Model):
    bought_item = models.ForeignKey(BoughtItem, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

member/forms.py
from django.forms import ModelForm
from .models import Message  # Import the Message model

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["message"]

member/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
import json
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from book.models import Book
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core import serializers
from main.models import Member
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from employee.models import Catalog
from member.models import CartItem, BoughtItem, PurchasedItem
from copy import deepcopy


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    books = Book.objects.all()
    member = get_object_or_404(Member, user=request.user)
    uang = member.money
    context = {
        'name': request.user.username,
        'books': books,
        'money': uang,
    }

    return render(request, "memberMember.html", context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:landing'))
    return response

@login_required(login_url='/login')
def get_books_json(request):
    books_user = Book.objects.filter()
    return HttpResponse(serializers.serialize('json', books_user))


@login_required(login_url='/login')
def show_books_bought(request):
    member = Member.objects.get(user=request.user)
    
    bought_items = BoughtItem.objects.filter(member=member)

    transactions_info = []
    for bought_item in bought_items:
        purchased_items = bought_item.purchaseditem_set.all()
        books_in_transaction = [{"title": purchased_item.book.title, "quantity": purchased_item.quantity} for purchased_item in purchased_items]
        transactions_info.append({
            "transaction_id": bought_item.id,
            "books": books_in_transaction,
            "date_added": bought_item.date_added,
            "notes": bought_item.notes
        })

    context = {
        'name': request.user.username,
        'transactions_info': transactions_info
    }

    return render(request, "buku_dibeli.html", context)

def get_cart(request):
    member = Member.objects.get(user=request.user)
    cart_items = CartItem.objects.filter(member=member)

    return HttpResponse(serializers.serialize('json', cart_items))

@csrf_exempt
@login_required(login_url='/login')
def add_book_to_cart(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        title = data.get('title')
        quantity = data.get('quantity')

        member = Member.objects.get(user=request.user)

        book, _ = Book.objects.get_or_create(title=title)

        cart_item, created = CartItem.objects.get_or_create(member=member, book=book)
        
        if not created:
            cart_item.quantity += quantity  # Menambahkan jumlah jika item sudah ada
        else:
            cart_item.quantity = quantity  # Atur jumlah baru jika item baru dibuat
        cart_item.save()

        cart_items = CartItem.objects.filter(member=member)
        cart_items_info = [{"title": item.book.title, "quantity": item.quantity} for item in cart_items]

        print(cart_items_info)

        return JsonResponse({"success": True})
    return JsonResponse({"success": False})

@csrf_exempt
@login_required(login_url='/login')
def add_book_to_cart_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        title = data['title']
        quantity = data['quantity']

        member = Member.objects.get(user=request.user)

        book, _ = Book.objects.get_or_create(title=title)

        cart_item, created = CartItem.objects.get_or_create(member=member, book=book)
        
        if not created:
            cart_item.quantity += quantity  # Menambahkan jumlah jika item sudah ada
        else:
            cart_item.quantity = quantity  # Atur jumlah baru jika item baru dibuat
        cart_item.save()

        return JsonResponse({'status': 'success', 'message': 'Cart Successed'}, status=200)
    else:
        return HttpResponseNotFound({'status': 'error', 'message': 'Invalid request'}, status=404)
    
@csrf_exempt
@login_required(login_url='/login')
def edit_cart(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        title = data.get('title')
        quantity = data.get('quantity')

        member = Member.objects.get(user=request.user)

        book, _ = Book.objects.get_or_create(title=title)

        cart_item, _ = CartItem.objects.get_or_create(member=member, book=book)

        cart_item.quantity = quantity

        cart_item.save()

        return JsonResponse({"success": True})
    return JsonResponse({"success": False})

@login_required(login_url='/login')
def get_money(request):
    member = get_object_or_404(Member, user=request.user)
    uang = member.money
    return HttpResponse(uang)

@csrf_exempt
def add_money(request):
    if request.method == 'POST':
            new_money = int(request.POST.get('newMoney'))  # Get the new money amount from the request
            member = get_object_or_404(Member, user=request.user)
            member.money += new_money
            member.save()
            return JsonResponse({'success': True, 'new_money': member.money})
    

def get_pesanan(request):
    member = get_object_or_404(Member, user=request.user)
    pesanan = member.pesanan
    return HttpResponse(pesanan)

@login_required(login_url='/login')
def tambah_ke_keranjang(request, **kwargs):
    member = get_object_or_404(Member, user=request.user)
    book = Book.objects.filter(id=kwargs.get('item_id', "")).first()
    if book in request.user.member.buku_dibeli.all():
        messages.info(request, 'Book is already in your cart')
        return redirect(reverse('member:show_main'))

def shopping_cart(request):
    member = Member.objects.get(user=request.user)
    cart_items = CartItem.objects.filter(member=member)
    uang = member.money

    total_harga = 0
    for i in cart_items:
        if i.book.harga == None:
            i.book.harga = 100000

        total_harga += i.book.harga*i.quantity

    cart_items = [{"title": item.book.title, "quantity": item.quantity, "harga": item.book.harga} for item in cart_items]

    context = {
        'name': request.user.username,
        'cart_items': cart_items,
        'uang': uang,
        'total_harga': total_harga,
    }

    return render(request, "shopping_cart.html", context)

def delete_cart(request, title):
    member = Member.objects.get(user=request.user)
    book = Book.objects.get(title=title)
    cart_item = CartItem.objects.filter(member=member, book=book).first()

    if cart_item:
        cart_item.delete()
    else:
        # Handle the case where the cart item doesn't exist
        pass

    return redirect('member:shopping_cart')

@csrf_exempt
def confirm_purchase(request):
    if request.method == 'POST':
        member = Member.objects.get(user=request.user)
        data = json.loads(request.body)
        notes = data.get('purchaseNotes', '')

        cart_items = CartItem.objects.filter(member=member)
        bought_item = BoughtItem(
            member=member,
            notes=notes,
        )
        bought_item.save()
        
        for item in cart_items:
            PurchasedItem.objects.create(
                bought_item=bought_item,
                member=member,
                book=item.book,
                quantity=item.quantity,
            )

        cart_items.delete()
        
        # Kembali ke halaman dengan menggunakan AJAX response
        return JsonResponse({'status': 'success', 'message': 'Purchase confirmed'}, status=200)
    else:
        return HttpResponseNotFound({'status': 'error', 'message': 'Invalid request'}, status=404)
    
@csrf_exempt
def confirm_purchase_flutter(request):
    if request.method == 'POST':
        member = Member.objects.get(user=request.user)
        data = json.loads(request.body)
        notes = data["notes"]

        cart_items = CartItem.objects.filter(member=member)

        total_price = 0
        for item in cart_items:
            # Update jumlah_buku and jumlah_terjual
            book = item.book
            book.jumlah_buku -= item.quantity
            book.jumlah_terjual += item.quantity
            book.save()

            # Calculate total price
            total_price += item.quantity * book.harga


        # Check if member has enough money
        if member.money >= total_price:
            bought_item = BoughtItem(
                member=member,
                notes=notes,
            )
            bought_item.save()

            for item in cart_items:
                # Create PurchasedItem
                PurchasedItem.objects.create(
                    bought_item=bought_item,
                    member=member,
                    book=item.book,
                    quantity=item.quantity,
                )

            
            # Deduct total price from member's money
            member.money -= total_price
            member.save()
            # Delete cart items after purchase
            cart_items.delete()

            # Return success response
            return JsonResponse({'status': 'success', 'message': 'Purchase confirmed', 'money': member.money}, status=200)
        else:
            # Return error response if not enough money
            return JsonResponse({'status': 'error', 'message': 'Not enough money'}, status=400)
    else:
        return HttpResponseNotFound({'status': 'error', 'message': 'Invalid request'}, status=404)

member/templates/shopping_cart.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PagePerfect</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}">
</head>
<body>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Edit your Cart!</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="title" class="col-form-label">Title:</label>
                            <input type="text" class="form-control" id="title" name="title" readonly></input>
                        </div>
                        <div class="mb-3">
                            <label for="quantity" class="col-form-label">Quantity:</label>
                            <div class="input-group">
                                <button type="button" class="btn btn-secondary" onclick="decrementQuantity()">-</button>
                                <input type="text" class="form-control text-center" id="quantity" name="quantity" value="1">
                                <button type="button" class="btn btn-secondary" onclick="incrementQuantity()">+</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_form" data-bs-dismiss="modal">Confirm</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Buy -->
    <div class="modal fade" id="buyModal" tabindex="-1" aria-labelledby="buyModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="buyModalLabel">Confirm Your Purchase</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="buyForm" onsubmit="return false;">
                        {% csrf_token %}
                        <!-- Anda dapat menambahkan detail tambahan di sini sesuai kebutuhan -->
                        <div class="mb-3">
                            <label for="totalPrice" class="form-label">Total Price:</label>
                            <input type="text" class="form-control" id="totalPrice" name="totalPrice" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="userMoney" class="form-label">Your Balance:</label>
                            <input type="text" class="form-control" id="userMoney" name="userMoney" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="purchaseNotes" class="form-label">Notes:</label>
                            <textarea class="form-control" id="purchaseNotes" name="purchaseNotes" rows="3"></textarea>
                        </div>
                        <!-- Tambahkan detail lain jika diperlukan -->
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="confirmPurchaseButton">Confirm Purchase</button>
                </div>
            </div>
        </div>
    </div>


    <style>

        .landing-section-book{

            display: flex;
            justify-content: center;
            align-items: center;
        }        

        .landing-section {
        min-height: 100vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        }
    
        .landing-main { 
        background: url(https://basecamplive.com/wp-content/uploads/2023/02/books.jpeg) no-repeat center center fixed; 
        background-size: cover;
        }
    
        .landing-section-content {
        padding: 2rem;
        background: rgba(0,0,0,0.5);
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
        }
    
        .brand {
        margin: 0;
        color: #1768BE;
        }
    
        .brand-text {
        color: #1768BE;
        }


        .card {
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin: 10px;
            width: calc(33.33% - 20px); /* 3 item per baris */
            background-color: #fff;
        }

        .card-container {
            margin-top: 8px;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); 
            flex-wrap: nowrap; 
            justify-content: flex-start; 
            gap: 5px;
            overflow-x: auto; 
            justify-items: center; 
            align-items: center;
            justify-content: center;
            margin: 28px;
        }

        .buy_button{
            margin-top: 20px;
            width: 150px;
        }
    </style>

<header class="header">
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'member:show_main' %}">PagePerfect</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'member:show_books_bought' %}">Books Bought</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>
</header>
    <section class="landing-section landing-main">
        <div class="landing-section-content">
            <h1 class="landing-main-text">
                Welcome {{name}}
            </h1>
            <h2>
                Here are the books you have in your cart!
            </h2>
            <div id="product_card" class="container_cards container card-container"></div>
            <p class="landing-main-text">
            </p>
            <h1>
                <span class="brand">P</span>age
                <span class="brand">P</span>erfect
            </h1>
            <p class="landing-main-text">
            </p>
        </div>

        <div id="dataContainer" data-total-harga="{{ total_harga }}" data-uang="{{ uang }}" style="display:none;"></div>
        <button type="button" class="buy_button btn btn-success" data-bs-toggle="modal" data-bs-target="#buyModal" onclick="preparePurchase()">Buy</button>

        <div class="container_cards container card-container">
            {% for cart in cart_items %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ cart.title }}</h5>
                        <p class="card-text">Harga: {{ cart.harga }}</p>
                        <p class="card-text">Quantity: {{ cart.quantity }}</p>
                        
                        <a href="{% url 'member:delete_cart' title=cart.title %}">
                            <button type="button" class="btn btn-danger">Delete</button>
                        </a>
                        <button type="button" class="btn btn-primary" onclick="setBookTitleInModal('{{ cart.title }}', '{{ cart.quantity }}')" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    <section class="landing-section-book">

    </section>
    
</body>

<script>

    document.getElementById("button_form").addEventListener("click", function() {
        const title = document.getElementById('title').value;
        const quantity = parseInt(document.getElementById('quantity').value);
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

        fetch("{% url 'member:edit_cart' %}", {
            method: "POST",
            body: JSON.stringify({ title: title, quantity: quantity }),
            headers: {
                "X-CSRFToken": csrftoken,
                "Content-Type": "application/json"
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                console.log("Book added to cart");
                window.location.href = '';
            } else {
                console.error("Failed to add book");
            }
        });
    });


    function setBookTitleInModal(title, quantity) {
        document.getElementById('title').value = title;
        document.getElementById('quantity').value = quantity;
    }

    function incrementQuantity() {
        var quantityInput = document.getElementById('quantity');
        var currentQuantity = parseInt(quantityInput.value);
        quantityInput.value = currentQuantity + 1;
    }

    function decrementQuantity() {
        var quantityInput = document.getElementById('quantity');
        var currentQuantity = parseInt(quantityInput.value);
        if (currentQuantity > 1) {
            quantityInput.value = currentQuantity - 1;
        }
    }

    function preparePurchase() {
        // Ambil elemen yang memiliki data-total-harga dan data-uang
        var dataContainer = document.getElementById('dataContainer');
        var totalPrice = dataContainer.getAttribute('data-total-harga');
        var userMoney = dataContainer.getAttribute('data-uang');

        // Set nilai ke dalam modal
        document.getElementById('totalPrice').value = totalPrice;
        document.getElementById('userMoney').value = userMoney;

        
    }

    document.getElementById("confirmPurchaseButton").addEventListener("click", function() {
        const notes = document.getElementById('purchaseNotes').value || ''; 
        const totalPrice = document.getElementById('totalPrice').value;
        const userMoney = document.getElementById('userMoney').value;
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

        if (parseInt(userMoney) >= parseInt(totalPrice)) {
            fetch("{% url 'member:confirm_purchase' %}", {
                method: "POST",
                body: JSON.stringify({ purchaseNotes: notes }),
                headers: {
                    "X-CSRFToken": csrftoken,
                    "Content-Type": "application/json"
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    // Handle success (e.g., show message, redirect, etc.)
                    console.log(data.message);
                    window.location.href = "{% url 'member:show_books_bought' %}";
                } else {
                    // Handle error
                    console.error("Failed to confirm purchase");
                }
            });
        } else {
            // Handle insufficient funds
            console.error("Insufficient funds to complete the purchase");
        }
    });




</script>

</html>