PagePerfect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('member/', include('member.urls')),
    path('writer/', include("writer.urls")),
    path('employee/', include("employee.urls")),
    path('auth/', include("authentication.urls"))
]

book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_boks'),
]

main/urls.py
from django.urls import path
from . import views
from main.views import register, login_user, landing, logout_user, show_mainMember, show_mainWriter, show_mainEmployee
app_name = 'main'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('mainMember/', show_mainMember, name='show_mainMember'),
    path('mainWriter/', show_mainWriter, name='show_mainWriter'),
    path('mainEmployee/', show_mainEmployee, name='show_mainEmployee'),
    path('logout/', logout_user, name='logout')
]

writer/urls.py
from django.urls import path
from . import views

app_name = 'writer'

urlpatterns = [
    path('get-product/', views.get_book_json, name="get_book_json"),
    path('get-acc-product/', views.get_acc_book_json, name="get_acc_book_json"),
    path('get-waiting-product/', views.get_waiting_book_json, name="get_waiting_book_json"),
    path('get-denied-product/', views.get_denied_book_json, name="get_denied_book_json"),
    path('create-product-ajax/', views.add_book_ajax, name="add_book_ajax"),
    path('show-collection/', views.show_collection, name="show_collection"),
    path('show-status-book/', views.show_status_book, name="show_status_book"),
    path('show-revenue/', views.show_revenue, name="show_revenue"),
    path('json/', views.show_json, name='show_json'),
    path('create-flutter/', views.create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

# Create your models here.



class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    revenue = models.BigIntegerField(default=0)
    role = models.CharField(max_length=20, default='Writer')

class Member(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    money = models.BigIntegerField(default=100000)
    role = models.CharField(max_length=20, default='Member')
    buku_dibeli = models.ManyToManyField(Book, blank=True)

class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, default='Employee')

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Member, Employee, Author
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
import json
from django.contrib.auth.models import User
from django.contrib.auth import logout


# Create your views here.

def landing(request):
    return render(request, 'landing.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            role = None

            if Member.objects.filter(user=user).exists():
                role = 'Member'
            elif Author.objects.filter(user=user).exists():
                role = 'Writer'
            elif Employee.objects.filter(user=user).exists():
                role = 'Employee'

            if role is not None:

                if role == 'Member':
                    return redirect('member:show_main')
                elif role == 'Writer':
                    return redirect('main:show_mainWriter')
                else:
                    return redirect('employee:main')
            else :
                return redirect('main:landing')
            
    context = {}
    return render(request, 'formLogin.html', context)


def register(request):
    if request.method == 'POST':
        if 'role' in request.POST:
            name = request.POST.get('username')
            password = request.POST.get('password')

            hashed_password = make_password(password)

            if request.POST['role'] == 'Member':
                user = User.objects.create(username=name, password=hashed_password)
                member = Member(user=user)
                member.save()
                return JsonResponse({'success': True})
            elif request.POST['role'] == 'Writer':
                user = User.objects.create(username=name, password=hashed_password)
                writer = Author(user=user)
                writer.save()
                return JsonResponse({'success': True})
            elif request.POST['role'] == 'Employee':
                user = User.objects.create(username=name, password=hashed_password)
                employee = Employee(user=user)
                employee.save()
                return JsonResponse({'success': True})
            return JsonResponse({'success': False, 'error_message': 'Invalid registration data'})
    return render(request, 'formRegister.html')

@login_required(login_url='/login')
def show_mainWriter(request):

    context = {
        'name': request.user.username,
    }

    return render(request, "mainWriter.html", context)

@login_required(login_url='/login')
def show_mainEmployee(request):
    return redirect('employee:main')

@login_required(login_url='/login')
def show_mainMember(request):

    context = {
        'name': request.user.username,
    }

    return render(request, "mainMember.html", context)
  
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:landing'))
    return response

main/templates/formLogin.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}


{% block content %}
    <style>

    .divider:after,
    .divider:before {
    content: "";
    flex: 1;
    height: 1px;
    background: #eee;
    }
    .h-custom {
    height: calc(100% - 73px);
    }
    @media (max-width: 450px) {
    .h-custom {
    height: 100%;
    }
    }


    </style>


<form class="vh-100" method="POST" action="{% url 'main:login' %}">
    {% csrf_token %}
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                    class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form>

                    <div class="divider d-flex align-items-center my-4">
                        <p class="text-center fw-bold mx-3 mb-0">Log In</p>
                    </div>

                    <!-- Email input -->

                    <div class="form-outline mb-4">
                        <input type="text" id="form3Example3" class="form-control form-control-lg"
                            placeholder="Enter a valid username" name="username" />
                        <label class="form-label" for="form3Example3">Username</label>
                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-3">
                        <input type="password" id="form3Example4" class="form-control form-control-lg"
                            placeholder="Enter password" name="password" />
                        <label class="form-label" for="form3Example4">Password</label>
                    </div>

                    <div class="text-center text-lg-start mt-4 pt-2">
                        <button type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                        <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'main:register' %}"
                                class="link-danger">Register</a></p>
                    </div>
            
                    </form>
                </div>
            </div>
            </div>
            <div
            class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
                <!-- Copyright -->
                <div class="text-white mb-3 mb-md-0">
                    Copyright © 2020. All rights reserved.
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

main/templates/formRegister.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    .formCheckbox{
        margin-left: 15px;
        margin-right: 15px;
    }

</style>

<form class="vh-100" style="background-color: #eee;" method="POST" action="" id="registration-form">
    {% csrf_token %}
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Register</p>
  
                  <form class="mx-1 mx-md-4">
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" id="name" name="username" class="form-control" required/>
                        <label class="form-label" for="form3Example1c">Username</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" id="password" name="password" class="form-control" required/>
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>

                    <div class="form-check d-flex justify-content-center mb-5">
                        <input class="formCheckbox" type="checkbox" name="role" value="Member" id="form2Example3c" />
                        <label class="form-check-label" for="form2Example3">
                          Member
                        </label>

                        <input class="formCheckbox" type="checkbox" name="role" value="Writer" id="form2Example3c" />
                        <label class="form-check-label" for="form2Example3">
                          Writer
                        </label>

                        <input class="formCheckbox" type="checkbox" name="role" value="Employee" id="form2Example3c" />
                        <label class="form-check-label" for="form2Example3">
                          Employee
                        </label>
                    </div>
  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    </div>
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <form>

  <!-- Tambahkan jQuery jika belum ada -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Tambahkan script Ajax untuk mengirim data registrasi -->
  <script>
  $(document).ready(function() {
      $('#registration-form').submit(function(event) {
          event.preventDefault();

          // Ambil data dari formulir
          var formData = $(this).serialize();

          // Kirim data melalui Ajax
          $.ajax({
              url: '{% url "main:register" %}',
              type: 'POST',
              data: formData,
              success: function(response) {
                  if (response.success) {
                      // Registrasi berhasil, Anda dapat mengarahkan pengguna ke halaman lain
                      window.location.href = '{% url "main:landing" %}';
                  } else {
                      // Registrasi gagal, Anda dapat menampilkan pesan kesalahan
                      alert('Registration failed. Please check the errors.');
                  }
              }
          });
      });
  });
  </script>


{% endblock content %}

main/templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PagePerfect</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pages/style.css' %}">
</head>
<body>

    <style>

        .landing-section-book{

            display: flex;
            justify-content: center;
            align-items: center;
        }        

        .landing-section {
        min-height: 100vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        }
    
        .landing-main { 
        background: url(https://basecamplive.com/wp-content/uploads/2023/02/books.jpeg) no-repeat center center fixed; 
        background-size: cover;
        }
    
        .landing-section-content {
        padding: 2rem;
        background: rgba(0,0,0,0.5);
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
        }
    
        .brand {
        margin: 0;
        color: #1768BE;
        }
    
        .brand-text {
        color: #1768BE;
        }
    </style>

    <header class="header">
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">PagePerfect</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:login' %}">Login</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <section class="landing-section landing-main">
        <div class="landing-section-content">
            <h1>
                <span class="brand">P</span>age
                <span class="brand">P</span>erfect
            </h1>
            <p class="landing-main-text">
                Got tired of missing out on releases from your favourite author?
                <br>
                You have found a perfect solution...
            </p>
        </div>
    </section>
    <section class="landing-section-book">

    </section>
    
</body>
</html>

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

</div>

{% endblock content %}   

main/templates/mainEmployee.html
{% extends 'base.html'%}

{% block content %}

    <h1>Main Employee</h1>

    <h5 class = "nama">Name:</h5>
    <p>{{name}}</p>

    <h5>Class:</h5>
    <p>{{class}}</p>

    <a href="{% url 'main:logout' %}">
        <button>
            Logout
        </button>
    </a>

{% endblock content %}

main/templates/mainMember.html
{% extends 'base.html'%}

{% block content %}

    <h1>Main Member</h1>

    <h5 class = "nama">Name:</h5>
    <p>{{name}}</p>

    <h5>Class:</h5>
    <p>{{class}}</p>

    <a href="{% url 'main:logout' %}">
        <button>
            Logout
        </button>
    </a>

{% endblock content %}

main/templates/mainWriter.html
{% extends 'base.html' %}
{% block content %}
<style>
    h2 {
        text-align: center;
    }
    .landing-section-book{

      display: flex;
      justify-content: center;
      align-items: center;
    }        

    .landing-section {
    min-height: 100vh;
    width: 100vw;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    }

    .landing-main { 
    background: url(https://basecamplive.com/wp-content/uploads/2023/02/books.jpeg) no-repeat center center fixed; 
    background-size: cover;
    }

    .landing-section-content {
    padding: 2rem;
    background: rgba(0,0,0,0.5);
    width: 100vw;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    color: #ccc;
    }

    .brand {
    margin: 0;
    color: #1768BE;
    }

    .container{
      text-align: center;
    }

    .brand-text {
    color: #1768BE;
    }

    div.one {
      margin-top: 40px;
      text-align: center;
    }

    button {
      margin-top: 10px;
    }
    #judul {
      color : rgb(128, 0, 113);
      font-size: 40px;
      font-weight: bold;
      font-style: italic;
  }

</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
          <a class="navbar-brand" href="#">{{ name }}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a href="{% url 'main:logout' %}">
                    <button type="button" class="btn btn-danger" style="margin-left: 10px;">Logout</button>
                </a>
            </div>
        </div>
    </div>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form id="form" onsubmit="return false;">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="title" class="col-form-label">Title:</label>
                      <input type="text" class="form-control" id="title" name="title" ></input>
                  </div>
                  <div class="mb-3">
                      <label for="harga" class="col-form-label">Harga:</label>
                      <input type="number" class="form-control" id="harga" name="harga"></input>
                  </div>
                  <div class="mb-3">
                    <label for="jumlah_buku" class="col-form-label">Jumlah Buku:</label>
                    <input type="number" class="form-control" id="jumlah_buku" name="jumlah_buku"></input>
                </div>
              </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
          </div>
      </div>
  </div>
</div>

<br>

<div class="container">
  <h2>What are you gonna do?</h2>
  <br>
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Publish Your Creation</h5>
          <p class="card-text">Click to publish your work</p>
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Publish</button>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">View Your Personal Creation</h5>
          <p class="card-text">Click to view your published work</p>
          <a href="{% url 'writer:show_collection' %}" class="btn btn-info">View</a>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">View Your Status Creation Feedback</h5>
          <p class="card-text">Click to view the status of your work</p>
          <a href="{% url 'writer:show_status_book' %}" class="btn btn-warning">View</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">View Your Treasury</h5>
          <p class="card-text">See your earnings and treasury</p>
          <a href="{% url 'writer:show_revenue' %}" class="btn btn-success">View</a>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    async function getBooks() {
        return fetch("{% url 'writer:get_book_json' %}").then((res) => res.json())
    }

    async function refreshBooks() {
      document.getElementById("product_cards").innerHTML = "";
      const books = await getBooks();
      let htmlString = "";
      books.forEach((book) => {
          htmlString += `
          <div class="card col-md-4">
              <div class="card-body">
                  <h5 class="card-title">${book.fields.title}</h5>
                  <p class="card-text">Author: ${book.fields.authors}</p>
                  <p class="card-text">Price: ${book.fields.harga}</p>
                  <p class="card-text">Stock: ${book.fields.jumlah_buku}</p>
                  <p class="card-text">Sold: ${book.fields.jumlah_terjual}</p>
              </div>
          </div>`;
      });
      document.getElementById("product_cards").innerHTML = htmlString;
      
  }
  
    refreshBooks()
    function addBook() {
      fetch("{% url 'writer:add_book_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshBooks)

      document.getElementById("form").reset()
      return false
    }

    document.getElementById("button_add").onclick = addBook

</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}